In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import pandas as pd
%matplotlib inline
import os


In [2]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Select the Runtime → "Change runtime type" menu to enable a GPU accelerator, ')
  print('and then re-execute this cell.')
else:
  print(gpu_info)

/bin/bash: nvidia-smi: command not found


In [3]:
# import os
# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials

In [4]:
# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

In [5]:
# from google.colab import drive 
# drive.mount('/content/gdrive/')

In [6]:
# import os
# os.chdir('/content/gdrive/My Drive/Colab Notebooks/dataset2')

In [6]:
path = os.getcwd()
f = []
for file in os.listdir('.'):
    if file.endswith('.jpg'):
        f.append(file)

In [8]:
len(f)

1122

In [9]:
df = pd.DataFrame()

In [10]:
df['img_name'] = np.array(f)

In [11]:
# Create Label 
df['label'] = np.nan
df['label'] = df['img_name'].apply(lambda x: x[0:6] if x.startswith('c') else
                                             x[0:4] if x.startswith('r') else 
                                             x[0:7] if x.startswith('su') else
                                             x[0:5] if x.startswith('sh') else np.nan)

# Create foders to contain training, validation and tesing data.

In [10]:
try:
    os.mkdir(path+"/"+"train")
except OSError:
    print ("Creation of the directory %s failed" % path+"/"+"train")
else:
    print ("Successfully created the directory %s " % path+"/"+"train")
try:
    os.mkdir(path+"/"+"test")
except OSError:
    print ("Creation of the directory %s failed" % path+"/"+"test")
else:
    print ("Successfully created the directory %s " % path+"/"+"test")
try:
    os.mkdir(path+"/"+"val")
except OSError:
    print ("Creation of the directory %s failed" % path+"/"+"val")
else:
    print ("Successfully created the directory %s " % path+"/"+"val")

Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /train
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /test
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /val


In [11]:
list_label = df.label.unique().tolist()

In [12]:
for i in list_label:
    try:
        os.mkdir(path+"/"+"train"+"/"+i)
    except OSError:
        print ("Creation of the directory %s failed" % path+"/"+"train"+"/"+i)
    else:
        print ("Successfully created the directory %s " % path+"/"+"train"+"/"+i)
for i in list_label:
    try:
        os.mkdir(path+"/"+"test"+"/"+i)
    except OSError:
        print ("Creation of the directory %s failed" % path+"/"+"test"+"/"+i)
    else:
        print ("Successfully created the directory %s " % path+"/"+"test"+"/"+i)
for i in list_label:
    try:
        os.mkdir(path+"/"+"val"+"/"+i)
    except OSError:
        print ("Creation of the directory %s failed" % path+"/"+"val"+"/"+i)
    else:
        print ("Successfully created the directory %s " % path+"/"+"val"+"/"+i)
    

Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /train/cloudy
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /train/rain
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /train/shine
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /train/sunrise
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /test/cloudy
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /test/rain
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /test/shine
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /test/sunrise
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /val/cloudy
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /val/rain
Successfully created the directory /home/vpasharawipas1/Deep/Weather_data /val/shine
Successfully created the directory /home/vpashara

#### Copy data to its appropiate folder based on the index after splitting

In [13]:
all_idx = [x for x in range(df.shape[0])]
train_all_idx = list(np.random.choice(all_idx, int(len(all_idx)*0.8),replace = False))
test_idx = list(set(all_idx) - set(train_all_idx))
train_idx = list(np.random.choice(train_all_idx, int(len(train_all_idx)*0.8),replace = False))
val_idx = list(set(train_all_idx) - set(train_idx))

In [14]:
from shutil import copyfile
for idx in train_idx:
    src = path + '/' + df.iloc[idx]['img_name']
    dst = path + '/' + 'train' + '/' + df.iloc[idx]['label'] + '/' + df.iloc[idx]['img_name']
    copyfile(src, dst)

In [15]:
from shutil import copyfile
for idx in test_idx:
    src = path + '/' + df.iloc[idx]['img_name']
    dst = path + '/' + 'test' + '/' + df.iloc[idx]['label'] + '/' + df.iloc[idx]['img_name']
    copyfile(src, dst)

In [16]:
from shutil import copyfile
for idx in val_idx:
    src = path + '/' + df.iloc[idx]['img_name']
    dst = path + '/' + 'val' + '/' + df.iloc[idx]['label'] + '/' + df.iloc[idx]['img_name']
    copyfile(src, dst)

#### Setting Dir

In [12]:
train_dir = os.path.join(path, 'train')
validation_dir = os.path.join(path, 'val')
test_dir = os.path.join(path, 'test')

#Directory with our training set
train_rain_dir = os.path.join(train_dir, 'rain')
train_cloudy_dir = os.path.join(train_dir, 'cloudy')
train_sunrise_dir = os.path.join(train_dir, 'sunrise')
train_shine_dir = os.path.join(train_dir, 'shine')

#Directory with our validation set
validation_rain_dir = os.path.join(validation_dir, 'rain')
validation_cloudy_dir = os.path.join(validation_dir, 'cloudy')
validation_sunrise_dir = os.path.join(validation_dir, 'sunrise')
validation_shine_dir = os.path.join(validation_dir, 'shine')

#Directory with our testing set
test_rain_dir = os.path.join(test_dir, 'rain')
test_cloudy_dir = os.path.join(test_dir, 'cloudy')
test_sunrise_dir = os.path.join(test_dir, 'sunrise')
test_shine_dir = os.path.join(test_dir, 'shine')

In [13]:
num_rain_tr = len(os.listdir(train_rain_dir))
num_cloudy_tr = len(os.listdir(train_cloudy_dir))
num_sunrise_tr = len(os.listdir(train_sunrise_dir))
num_shine_tr = len(os.listdir(train_shine_dir))

num_rain_val = len(os.listdir(validation_rain_dir))
num_cloudy_val = len(os.listdir(validation_cloudy_dir))
num_sunrise_val = len(os.listdir(validation_sunrise_dir))
num_shine_val = len(os.listdir(validation_shine_dir))

num_rain_test = len(os.listdir(test_rain_dir))
num_cloudy_test = len(os.listdir(test_cloudy_dir))
num_sunrise_test = len(os.listdir(test_sunrise_dir))
num_shine_test = len(os.listdir(test_shine_dir))

total_train = num_rain_tr + num_cloudy_tr + num_sunrise_tr + num_shine_tr
total_val = num_rain_val + num_cloudy_val + num_sunrise_val + num_shine_val
total_test = num_rain_test + num_cloudy_test + num_sunrise_test + num_shine_test

print('total training rain images:', num_rain_tr)
print('total training cloudy images:', num_cloudy_tr)
print('total training sunrise images:', num_sunrise_tr)
print('total training shine images:', num_shine_tr)
print("--")
print('total validation rain images:', num_rain_val)
print('total validation cloudy images:', num_cloudy_val)
print('total validation sunrise images:', num_sunrise_val)
print('total validation shine images:', num_shine_val)
print("--")
print('total test rain images:', num_rain_test)
print('total test cloudy images:', num_cloudy_test)
print('total test sunrise images:', num_sunrise_test)
print('total test shine images:', num_shine_test)
print("--")
print("Total training images:", total_train)
print("Total validation images:", total_val)
print("Total test images:", total_test)

total training rain images: 139
total training cloudy images: 193
total training sunrise images: 236
total training shine images: 149
--
total validation rain images: 29
total validation cloudy images: 55
total validation sunrise images: 56
total validation shine images: 40
--
total test rain images: 45
total test cloudy images: 52
total test sunrise images: 64
total test shine images: 64
--
Total training images: 717
Total validation images: 180
Total test images: 225


# Modeling

In [30]:
# importing the libraries
from keras.models import Model
from keras.layers import Flatten, Dense
from keras.applications import VGG16
#from keras.preprocessing import image
IMAGE_SIZE = [256, 256]  
# we will keep the image size as (256,256). You can increase the size for better results. 

# loading the weights of VGG16 without the top layer. 
#These weights are trained on Imagenet dataset.
vgg = VGG16(input_shape = IMAGE_SIZE + [3], weights = 'imagenet', include_top = False)  
# input_shape = (256,256,3) as required by VGG

# this will exclude the initial layers from training phase as there are already been trained.
for layer in vgg.layers[:-8]:
    layer.trainable = False
for layer in vgg.layers[-8:]:
    layer.trainable = True
    
x = Flatten()(vgg.output)
x = Dense(128, activation = 'relu')(x)   # we can add a new fully connected layer but it will increase the execution time.
pred = Dense(4, activation = 'softmax')(x)  # adding the output layer with softmax function as this is a multi label classification problem.

model = Model(inputs = vgg.input, outputs = pred)

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [31]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 256, 256, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 256, 256, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 256, 256, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 128, 128, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 128, 128, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 128, 128, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 64, 64, 128)       0         
__________

#### Check the VGG layer status

In [32]:
for layer in vgg.layers:
    print(layer.trainable)

False
False
False
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True


#### Image Augmentation

In [70]:
# Image Augmentation

from keras.preprocessing.image import ImageDataGenerator
from keras.applications.vgg16 import preprocess_input

training_datagen = ImageDataGenerator(
                                    rescale=1./255,   # all pixel values will be between 0 an 1
                                    shear_range=0.2, 
                                    zoom_range=0.2,
                                    horizontal_flip=True,
                                    preprocessing_function=preprocess_input)
validation_datagen = ImageDataGenerator(rescale = 1./255, preprocessing_function=preprocess_input)
test_datagen = ImageDataGenerator(rescale = 1./255, preprocessing_function=preprocess_input)

training_generator = training_datagen.flow_from_directory(train_dir, target_size = IMAGE_SIZE, batch_size = 100, class_mode = 'categorical')
validation_generator = validation_datagen.flow_from_directory(validation_dir, target_size = IMAGE_SIZE, batch_size = 100, class_mode = 'categorical')
test_generator = test_datagen.flow_from_directory(test_dir, target_size = IMAGE_SIZE, batch_size = 100, class_mode = 'categorical',shuffle = False)


Found 717 images belonging to 4 classes.
Found 180 images belonging to 4 classes.
Found 225 images belonging to 4 classes.


## Train the model

### VGG

In [34]:
training_images = 717 
validation_images = 180
history = model.fit_generator(training_generator,
                   steps_per_epoch = 717,  # this should be equal to total number of images in training set. But to speed up the execution, I am only using 10000 images. Change this for better results. 
                   epochs = 2,  # change this for better results
                   validation_data = validation_generator,
                   validation_steps = 180)  # this should be equal to total number of images in validation set.

Epoch 1/2
717/717 [==============================] - 938s 1s/step - loss: 0.2135 - acc: 0.9202 - val_loss: 0.7213 - val_acc: 0.8667
Epoch 2/2
717/717 [==============================] - 921s 1s/step - loss: 0.0466 - acc: 0.9871 - val_loss: 0.2815 - val_acc: 0.9500


In [35]:
print ('Training Accuracy = ' + str(history.history['acc']))
print ('Validation Accuracy = ' + str(history.history['val_acc']))

Training Accuracy = [0.9194253161595908, 0.9872489537978199]
Validation Accuracy = [0.8666666679912143, 0.9499999947018094]


In [36]:
model.save('dl_fcl_v2.h5')
os.getcwd()

'/home/ubuntu'

In [50]:
# load saved models
from keras.models import load_model
image_cnn = load_model('dl_fcl_v2.h5')

Using TensorFlow backend.


### Model performance -VGG

In [54]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
#Confusion Matrix and Classification Report
Y_pred = image_cnn.predict_generator(test_generator, test_generator.samples // test_generator.batch_size + 1)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(test_generator.classes, y_pred))
print('Classification Report')
lables=['cloud','rain','shine','sunrise']
print(classification_report(test_generator.classes, y_pred, target_names=lables))

Confusion Matrix
[[43  0  5  4]
 [ 0 42  2  1]
 [ 1  1 61  1]
 [ 0  0  1 63]]
Classification Report
              precision    recall  f1-score   support

       cloud       0.98      0.83      0.90        52
        rain       0.98      0.93      0.95        45
       shine       0.88      0.95      0.92        64
     sunrise       0.91      0.98      0.95        64

    accuracy                           0.93       225
   macro avg       0.94      0.92      0.93       225
weighted avg       0.93      0.93      0.93       225



### CNN (customized layers)

In [16]:
# Image Augmentation

from keras.preprocessing.image import ImageDataGenerator
from keras.applications.vgg16 import preprocess_input

training_datagen = ImageDataGenerator(
                                    rescale=1./255,   # all pixel values will be between 0 an 1
                                    shear_range=0.2, 
                                    zoom_range=0.2,
                                    horizontal_flip=True,
                                    preprocessing_function=preprocess_input)

validation_datagen = ImageDataGenerator(rescale = 1./255, preprocessing_function=preprocess_input)

test_datagen = ImageDataGenerator(rescale = 1./255, preprocessing_function=preprocess_input)

training_generator = training_datagen.flow_from_directory(train_dir, target_size = IMAGE_SIZE
                                                          , batch_size =717, class_mode = 'categorical')
validation_generator = validation_datagen.flow_from_directory(validation_dir, target_size = IMAGE_SIZE
                                                              , batch_size = 180, class_mode = 'categorical')
test_generator = test_datagen.flow_from_directory(test_dir, target_size = IMAGE_SIZE
                                                  , batch_size = 225, class_mode = 'categorical',shuffle = False)



Found 717 images belonging to 4 classes.
Found 180 images belonging to 4 classes.
Found 225 images belonging to 4 classes.


In [44]:
print(training_generator[0][0][0].shape)
print(training_generator[0][1][0].shape)

(256, 256, 3)
(4,)


In [17]:
'''Setting up the features and lables to be suitable for TFLEARN'''
# X-Features & Y-Labels 
X = training_generator[0][0]
Y = training_generator[0][1] 
mytest_x = validation_generator[0][0]
mytest_y = validation_generator[0][1]
mytest_holdout_x = test_generator[0][0]
mytest_holdout_y = test_generator[0][1]

In [29]:
import tflearn 
from tflearn.layers.conv import conv_2d, max_pool_2d 
from tflearn.layers.core import input_data, dropout, fully_connected 
from tflearn.layers.estimator import regression 
import tensorflow as tf
LR = 1e-3
tf.reset_default_graph() 
convnet = input_data(shape =[None, 256 , 256 , 3], name ='input') # input (none, image heigt, image width, 3)
  
convnet = conv_2d(convnet, 32, 5, activation ='relu') 
convnet = max_pool_2d(convnet, 5) 
  
convnet = conv_2d(convnet, 64, 5, activation ='relu') 
convnet = max_pool_2d(convnet, 5) 
  
convnet = conv_2d(convnet, 128, 5, activation ='relu') 
convnet = max_pool_2d(convnet, 5) 
  
convnet = conv_2d(convnet, 64, 5, activation ='relu') 
convnet = max_pool_2d(convnet, 5) 
  
convnet = conv_2d(convnet, 32, 5, activation ='relu') 
convnet = max_pool_2d(convnet, 5) 
  
convnet = fully_connected(convnet, 1024, activation ='relu') 
convnet = dropout(convnet, 0.8) 
  
convnet = fully_connected(convnet, 4, activation ='softmax') # 4 is number of class
convnet = regression(convnet, optimizer ='adam', learning_rate = LR, 
      loss ='categorical_crossentropy', name ='targets') 
  
model = tflearn.DNN(convnet, tensorboard_dir ='log') 
 

In [35]:
import time
start = time.time()
model.fit({'input': X}, {'targets': Y}, n_epoch = 35,  
    validation_set =({'input': mytest_x}, {'targets': mytest_y}),  
    snapshot_step = 5, show_metric = True, run_id = 'MODEL_NAME') 
stop = time.time()
print("Time used: ", (stop-start)/60, " mins")


Training Step: 419  | total loss: 0.05171 | time: 30.411s
| Adam | epoch: 035 | loss: 0.05171 - acc: 0.9889 -- iter: 704/717
Training Step: 420  | total loss: 0.04747 | time: 35.224s
| Adam | epoch: 035 | loss: 0.04747 - acc: 0.9900 | val_loss: 0.15360 - val_acc: 0.9611 -- iter: 717/717
--
Time used:  21.236554809411366  mins


In [26]:
import time
start = time.time()
model.fit({'input': X}, {'targets': Y}, n_epoch = 25,  
    validation_set =({'input': mytest_x}, {'targets': mytest_y}),  
    snapshot_step = 5, show_metric = True, run_id = 'MODEL_NAME') 
stop = time.time()
print("Time used: ", (stop-start)/60, " mins")


Training Step: 299  | total loss: 0.12304 | time: 30.264s
| Adam | epoch: 025 | loss: 0.12304 - acc: 0.9594 -- iter: 704/717
Training Step: 300  | total loss: 0.11148 | time: 35.088s
| Adam | epoch: 025 | loss: 0.11148 - acc: 0.9634 | val_loss: 0.28713 - val_acc: 0.9111 -- iter: 717/717
--
Time used:  15.095795277754466  mins


In [30]:
import time
start = time.time()
model.fit({'input': X}, {'targets': Y}, n_epoch = 80,  
    validation_set =({'input': mytest_x}, {'targets': mytest_y}),  
    snapshot_step = 5, show_metric = True, run_id = 'MODEL_NAME') 
stop = time.time()
print("Time used: ", (stop-start)/60, " mins")

Training Step: 959  | total loss: 0.03713 | time: 32.856s
| Adam | epoch: 080 | loss: 0.03713 - acc: 0.9966 -- iter: 704/717
Training Step: 960  | total loss: 0.03393 | time: 37.579s
| Adam | epoch: 080 | loss: 0.03393 - acc: 0.9969 | val_loss: 0.13869 - val_acc: 0.9667 -- iter: 717/717
--
Time used:  48.18629100322723  mins


In [31]:
###save the model
model.save("cnn_customized") 
###To Load trained model 
#model.load('cnn_customized')

INFO:tensorflow:/home/vpasharawipas1/Deep/Weather_data/cnn_customized is not in all_model_checkpoint_paths. Manually adding it.


### Model performance - customized CNN

In [62]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
#Confusion Matrix and Classification Report
y_pred=model.predict(mytest_holdout_x)
y_pred= [ np.argmax(i)  for i in y_pred ]
print('Confusion Matrix')
print(confusion_matrix(test_generator.classes, y_pred))
print('Classification Report')
lables=['cloud','rain','shine','sunrise']
print(classification_report(test_generator.classes, y_pred, target_names=lables))

Confusion Matrix
[[48  0  2  0]
 [ 0 44  1  0]
 [ 4  2 50  1]
 [ 0  0  0 73]]
Classification Report
             precision    recall  f1-score   support

      cloud       0.92      0.96      0.94        50
       rain       0.96      0.98      0.97        45
      shine       0.94      0.88      0.91        57
    sunrise       0.99      1.00      0.99        73

avg / total       0.96      0.96      0.96       225



In [27]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
#Confusion Matrix and Classification Report
y_pred=model.predict(mytest_holdout_x)
y_pred= [ np.argmax(i)  for i in y_pred ]
print('Confusion Matrix')
print(confusion_matrix(test_generator.classes, y_pred))
print('Classification Report')
lables=['cloud','rain','shine','sunrise']
print(classification_report(test_generator.classes, y_pred, target_names=lables))

Confusion Matrix
[[42  2  8  0]
 [ 3 41  1  0]
 [ 4  1 58  1]
 [ 0  0  0 64]]
Classification Report
             precision    recall  f1-score   support

      cloud       0.86      0.81      0.83        52
       rain       0.93      0.91      0.92        45
      shine       0.87      0.91      0.89        64
    sunrise       0.98      1.00      0.99        64

avg / total       0.91      0.91      0.91       225



In [32]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
#Confusion Matrix and Classification Report
y_pred=model.predict(mytest_holdout_x)
y_pred= [ np.argmax(i)  for i in y_pred ]
print('Confusion Matrix')
print(confusion_matrix(test_generator.classes, y_pred))
print('Classification Report')
lables=['cloud','rain','shine','sunrise']
print(classification_report(test_generator.classes, y_pred, target_names=lables))

Confusion Matrix
[[48  1  3  0]
 [ 4 41  0  0]
 [ 8  0 55  1]
 [ 0  0  0 64]]
Classification Report
             precision    recall  f1-score   support

      cloud       0.80      0.92      0.86        52
       rain       0.98      0.91      0.94        45
      shine       0.95      0.86      0.90        64
    sunrise       0.98      1.00      0.99        64

avg / total       0.93      0.92      0.93       225

